### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Hekku2** [Hekku2/competition-status-server#2]
This issue contains roadmap for this project.

- [x] A base for protocol documentation [#1]
- [x] Base server and Docker compose base file [#3]
- [x] current-competitor API [#3]
- [x] Competition status server endpoint api [#3]
- [x] SignalR Server and client [#4]
- [x] Add forfeit competitors to bottom of result list [#5]
- [x] Generate documentation [#6]
- [x] performance-results API [#10]
- [x] Add signalrR message for updated results [#10]
- [x] Read current competitor from file [#7]
- [x] Add a simulator for easier testing [#8]
- [x] Base for frontend app [#11]
- [ ] Management app [#13]
- [ ] Scoreboard app [#12]
- [ ] Add a way to upload initial competition data from front end
- [x] Generate model document to /doc automatically [#15]
- [x] Update /doc content to match implementation  [#16]
- [ ] Support competitor who has competed but has not received results. That competitor shoul not be shown in "upcoming".
- [ ] Add a way to override placement (if calculation fails)
- [ ] Implement calculation and testing for even score.
- [ ] Implement API Key for management operations

V1.1

- [ ] Signal R connection status

V2
- [ ] UDP time server, test client and documentation
